version: "3.8"

services:
  postgres:
    image: postgres:18
    container_name: lab2-postgres
    environment:
      POSTGRES_DB: employeesbd
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    ports:
      - "5432:5432"
    volumes:
      - lab2-postgres-/var/lib/postgresql/data

volumes:
  lab2-postgres-